/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import TebexHeadless.JSON;

/**
 * CommunityGoalData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-24T11:21:56.600931566-05:00[America/Chicago]", comments = "Generator version: 7.5.0")
public class CommunityGoalData {
  public static final String SERIALIZED_NAME_HEADER = "header";
  @SerializedName(SERIALIZED_NAME_HEADER)
  private String header;

  /**
   * Gets or Sets barStyle
   */
  @JsonAdapter(BarStyleEnum.Adapter.class)
  public enum BarStyleEnum {
    NORMAL("normal"),
    
    STRIPED("striped");

    private String value;

    BarStyleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BarStyleEnum fromValue(String value) {
      for (BarStyleEnum b : BarStyleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BarStyleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BarStyleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BarStyleEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BarStyleEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BarStyleEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BAR_STYLE = "bar_style";
  @SerializedName(SERIALIZED_NAME_BAR_STYLE)
  private BarStyleEnum barStyle;

  public static final String SERIALIZED_NAME_BAR_ANIMATED = "bar_animated";
  @SerializedName(SERIALIZED_NAME_BAR_ANIMATED)
  private Boolean barAnimated;

  public static final String SERIALIZED_NAME_PERCENTAGE = "percentage";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE)
  private BigDecimal percentage;

  public static final String SERIALIZED_NAME_TOTAL_PAYMENTS = "total_payments";
  @SerializedName(SERIALIZED_NAME_TOTAL_PAYMENTS)
  private BigDecimal totalPayments;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  private BigDecimal target;

  public static final String SERIALIZED_NAME_TIMES_ACHIEVED = "times_achieved";
  @SerializedName(SERIALIZED_NAME_TIMES_ACHIEVED)
  private Integer timesAchieved;

  public CommunityGoalData() {
  }

  public CommunityGoalData header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Get header
   * @return header
  **/
  @javax.annotation.Nonnull
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }


  public CommunityGoalData barStyle(BarStyleEnum barStyle) {
    this.barStyle = barStyle;
    return this;
  }

   /**
   * Get barStyle
   * @return barStyle
  **/
  @javax.annotation.Nonnull
  public BarStyleEnum getBarStyle() {
    return barStyle;
  }

  public void setBarStyle(BarStyleEnum barStyle) {
    this.barStyle = barStyle;
  }


  public CommunityGoalData barAnimated(Boolean barAnimated) {
    this.barAnimated = barAnimated;
    return this;
  }

   /**
   * Get barAnimated
   * @return barAnimated
  **/
  @javax.annotation.Nonnull
  public Boolean getBarAnimated() {
    return barAnimated;
  }

  public void setBarAnimated(Boolean barAnimated) {
    this.barAnimated = barAnimated;
  }


  public CommunityGoalData percentage(BigDecimal percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * minimum: 0
   * maximum: 100
   * @return percentage
  **/
  @javax.annotation.Nonnull
  public BigDecimal getPercentage() {
    return percentage;
  }

  public void setPercentage(BigDecimal percentage) {
    this.percentage = percentage;
  }


  public CommunityGoalData totalPayments(BigDecimal totalPayments) {
    this.totalPayments = totalPayments;
    return this;
  }

   /**
   * Optional, present depending on module configuration.
   * @return totalPayments
  **/
  @javax.annotation.Nullable
  public BigDecimal getTotalPayments() {
    return totalPayments;
  }

  public void setTotalPayments(BigDecimal totalPayments) {
    this.totalPayments = totalPayments;
  }


  public CommunityGoalData target(BigDecimal target) {
    this.target = target;
    return this;
  }

   /**
   * Optional, present depending on module configuration.
   * @return target
  **/
  @javax.annotation.Nullable
  public BigDecimal getTarget() {
    return target;
  }

  public void setTarget(BigDecimal target) {
    this.target = target;
  }


  public CommunityGoalData timesAchieved(Integer timesAchieved) {
    this.timesAchieved = timesAchieved;
    return this;
  }

   /**
   * Optional, present depending on module configuration.
   * @return timesAchieved
  **/
  @javax.annotation.Nullable
  public Integer getTimesAchieved() {
    return timesAchieved;
  }

  public void setTimesAchieved(Integer timesAchieved) {
    this.timesAchieved = timesAchieved;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunityGoalData communityGoalData = (CommunityGoalData) o;
    return Objects.equals(this.header, communityGoalData.header) &&
        Objects.equals(this.barStyle, communityGoalData.barStyle) &&
        Objects.equals(this.barAnimated, communityGoalData.barAnimated) &&
        Objects.equals(this.percentage, communityGoalData.percentage) &&
        Objects.equals(this.totalPayments, communityGoalData.totalPayments) &&
        Objects.equals(this.target, communityGoalData.target) &&
        Objects.equals(this.timesAchieved, communityGoalData.timesAchieved);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(header, barStyle, barAnimated, percentage, totalPayments, target, timesAchieved);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunityGoalData {\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    barStyle: ").append(toIndentedString(barStyle)).append("\n");
    sb.append("    barAnimated: ").append(toIndentedString(barAnimated)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    totalPayments: ").append(toIndentedString(totalPayments)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    timesAchieved: ").append(toIndentedString(timesAchieved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("header");
    openapiFields.add("bar_style");
    openapiFields.add("bar_animated");
    openapiFields.add("percentage");
    openapiFields.add("total_payments");
    openapiFields.add("target");
    openapiFields.add("times_achieved");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("header");
    openapiRequiredFields.add("bar_style");
    openapiRequiredFields.add("bar_animated");
    openapiRequiredFields.add("percentage");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CommunityGoalData
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommunityGoalData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommunityGoalData is not found in the empty JSON string", CommunityGoalData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommunityGoalData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommunityGoalData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CommunityGoalData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("header").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `header` to be a primitive type in the JSON string but got `%s`", jsonObj.get("header").toString()));
      }
      if (!jsonObj.get("bar_style").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bar_style` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bar_style").toString()));
      }
      // validate the required field `bar_style`
      BarStyleEnum.validateJsonElement(jsonObj.get("bar_style"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommunityGoalData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommunityGoalData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommunityGoalData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommunityGoalData.class));

       return (TypeAdapter<T>) new TypeAdapter<CommunityGoalData>() {
           @Override
           public void write(JsonWriter out, CommunityGoalData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommunityGoalData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CommunityGoalData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CommunityGoalData
  * @throws IOException if the JSON string is invalid with respect to CommunityGoalData
  */
  public static CommunityGoalData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommunityGoalData.class);
  }

 /**
  * Convert an instance of CommunityGoalData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

