/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/TebexHeadless/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/TebexHeadless/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TebexHeadlessApi);
  }
}(this, function(expect, TebexHeadlessApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TebexHeadlessApi.Basket();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Basket', function() {
    it('should create an instance of Basket', function() {
      // uncomment below and update the code to test Basket
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be.a(TebexHeadlessApi.Basket);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property ident (base name: "ident")', function() {
      // uncomment below and update the code to test the property ident
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property complete (base name: "complete")', function() {
      // uncomment below and update the code to test the property complete
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property coupons (base name: "coupons")', function() {
      // uncomment below and update the code to test the property coupons
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property giftcards (base name: "giftcards")', function() {
      // uncomment below and update the code to test the property giftcards
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property creatorCode (base name: "creator_code")', function() {
      // uncomment below and update the code to test the property creatorCode
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property cancelUrl (base name: "cancel_url")', function() {
      // uncomment below and update the code to test the property cancelUrl
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property completeUrl (base name: "complete_url")', function() {
      // uncomment below and update the code to test the property completeUrl
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property completeAutoRedirect (base name: "complete_auto_redirect")', function() {
      // uncomment below and update the code to test the property completeAutoRedirect
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property usernameId (base name: "username_id")', function() {
      // uncomment below and update the code to test the property usernameId
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property basePrice (base name: "base_price")', function() {
      // uncomment below and update the code to test the property basePrice
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property salesTax (base name: "sales_tax")', function() {
      // uncomment below and update the code to test the property salesTax
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property totalPrice (base name: "total_price")', function() {
      // uncomment below and update the code to test the property totalPrice
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property packages (base name: "packages")', function() {
      // uncomment below and update the code to test the property packages
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new TebexHeadlessApi.Basket();
      //expect(instance).to.be();
    });

  });

}));
