/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/TebexHeadless/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/TebexHeadless/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TebexHeadlessApi);
  }
}(this, function(expect, TebexHeadlessApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TebexHeadlessApi.CreateBasketRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateBasketRequest', function() {
    it('should create an instance of CreateBasketRequest', function() {
      // uncomment below and update the code to test CreateBasketRequest
      //var instance = new TebexHeadlessApi.CreateBasketRequest();
      //expect(instance).to.be.a(TebexHeadlessApi.CreateBasketRequest);
    });

    it('should have the property completeUrl (base name: "complete_url")', function() {
      // uncomment below and update the code to test the property completeUrl
      //var instance = new TebexHeadlessApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property cancelUrl (base name: "cancel_url")', function() {
      // uncomment below and update the code to test the property cancelUrl
      //var instance = new TebexHeadlessApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instance = new TebexHeadlessApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property completeAutoRedirect (base name: "complete_auto_redirect")', function() {
      // uncomment below and update the code to test the property completeAutoRedirect
      //var instance = new TebexHeadlessApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

  });

}));
