/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BasketPackageInBasket } from './basketPackageInBasket';
import { RevenueShare } from './revenueShare';

/**
* A package within an existing basket.
*/
export class BasketPackage {
    /**
    * The package ID
    */
    'id'?: number;
    'description'?: string;
    'image'?: string;
    'name'?: string;
    'slug'?: string;
    'inBasket'?: BasketPackageInBasket;
    /**
    * The type of payment, either `single` for one-time payments or `subscription`.
    */
    'type'?: BasketPackage.TypeEnum;
    /**
    * An array of payment destination objects describing how the purchase should be split between multiple wallets. **Only available with pre-agreement from Tebex.**
    */
    'revenueShare'?: Array<RevenueShare>;
    /**
    * Whether this package is a recurring (subscription) purchase.
    */
    'isRecurring'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "inBasket",
            "baseName": "in_basket",
            "type": "BasketPackageInBasket"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BasketPackage.TypeEnum"
        },
        {
            "name": "revenueShare",
            "baseName": "revenue_share",
            "type": "Array<RevenueShare>"
        },
        {
            "name": "isRecurring",
            "baseName": "is_recurring",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BasketPackage.attributeTypeMap;
    }
}

export namespace BasketPackage {
    export enum TypeEnum {
        Single = <any> 'single',
        Subscription = <any> 'subscription'
    }
}
