/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BasketPackageInBasket {
    /**
    * The quantity of `package` in this basket. This is not the total quantity of overall items in the basket.
    */
    'quantity'?: number;
    'price'?: number;
    /**
    * The username id of the user this package is gifted to
    */
    'giftUsernameId'?: string;
    /**
    * The username of the user this package is gifted to.
    */
    'giftUsername'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "giftUsernameId",
            "baseName": "gift_username_id",
            "type": "string"
        },
        {
            "name": "giftUsername",
            "baseName": "gift_username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BasketPackageInBasket.attributeTypeMap;
    }
}

