/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TebexHeadless.Client.OpenAPIDateConverter;

namespace TebexHeadless.Model
{
    /// <summary>
    /// BasketPackageInBasket
    /// </summary>
    [DataContract(Name = "BasketPackage_in_basket")]
    public partial class BasketPackageInBasket : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BasketPackageInBasket" /> class.
        /// </summary>
        /// <param name="quantity">The quantity of &#x60;package&#x60; in this basket. This is not the total quantity of overall items in the basket..</param>
        /// <param name="price">price.</param>
        /// <param name="giftUsernameId">The username id of the user this package is gifted to.</param>
        /// <param name="giftUsername">The username of the user this package is gifted to..</param>
        public BasketPackageInBasket(int quantity = default(int), float price = default(float), string giftUsernameId = default(string), string giftUsername = default(string))
        {
            this.Quantity = quantity;
            this.Price = price;
            this.GiftUsernameId = giftUsernameId;
            this.GiftUsername = giftUsername;
        }

        /// <summary>
        /// The quantity of &#x60;package&#x60; in this basket. This is not the total quantity of overall items in the basket.
        /// </summary>
        /// <value>The quantity of &#x60;package&#x60; in this basket. This is not the total quantity of overall items in the basket.</value>
        /// <example>2</example>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public float Price { get; set; }

        /// <summary>
        /// The username id of the user this package is gifted to
        /// </summary>
        /// <value>The username id of the user this package is gifted to</value>
        [DataMember(Name = "gift_username_id", EmitDefaultValue = false)]
        public string GiftUsernameId { get; set; }

        /// <summary>
        /// The username of the user this package is gifted to.
        /// </summary>
        /// <value>The username of the user this package is gifted to.</value>
        [DataMember(Name = "gift_username", EmitDefaultValue = false)]
        public string GiftUsername { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BasketPackageInBasket {\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  GiftUsernameId: ").Append(GiftUsernameId).Append("\n");
            sb.Append("  GiftUsername: ").Append(GiftUsername).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
