/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TebexHeadless.Client.OpenAPIDateConverter;

namespace TebexHeadless.Model
{
    /// <summary>
    /// Package
    /// </summary>
    [DataContract(Name = "Package")]
    public partial class Package : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Package" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="image">image.</param>
        /// <param name="type">type.</param>
        /// <param name="category">category.</param>
        /// <param name="basePrice">basePrice.</param>
        /// <param name="salesTax">salesTax.</param>
        /// <param name="totalPrice">totalPrice.</param>
        /// <param name="currency">currency.</param>
        /// <param name="proratePrice">If this package is part of a tiered category, this is the difference on upgrade pricing from the current active tier..</param>
        /// <param name="discount">discount.</param>
        /// <param name="disableQuantity">disableQuantity.</param>
        /// <param name="disableGifting">disableGifting.</param>
        /// <param name="expirationDate">expirationDate.</param>
        /// <param name="media">media.</param>
        /// <param name="order">order.</param>
        /// <param name="slug">slug.</param>
        /// <param name="userLimit">userLimit.</param>
        /// <param name="creatorMetaData">creatorMetaData.</param>
        /// <param name="options">options.</param>
        /// <param name="variables">variables.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        /// <param name="ident">The package&#39;s string identifier..</param>
        /// <param name="vipStatus">The package&#39;s VIP status. Only &#x60;null&#x60; has been observed so far, so the non-null type is unconfirmed..</param>
        public Package(int id = default(int), string name = default(string), string description = default(string), string image = default(string), string type = default(string), PackageCategory category = default(PackageCategory), float basePrice = default(float), float salesTax = default(float), float totalPrice = default(float), string currency = default(string), float proratePrice = default(float), float discount = default(float), bool disableQuantity = default(bool), bool disableGifting = default(bool), DateTime expirationDate = default(DateTime), List<PackageMedia> media = default(List<PackageMedia>), int order = default(int), string slug = default(string), int userLimit = default(int), Object creatorMetaData = default(Object), List<string> options = default(List<string>), List<string> variables = default(List<string>), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), string ident = default(string), string vipStatus = default(string))
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Image = image;
            this.Type = type;
            this.Category = category;
            this.BasePrice = basePrice;
            this.SalesTax = salesTax;
            this.TotalPrice = totalPrice;
            this.Currency = currency;
            this.ProratePrice = proratePrice;
            this.Discount = discount;
            this.DisableQuantity = disableQuantity;
            this.DisableGifting = disableGifting;
            this.ExpirationDate = expirationDate;
            this.Media = media;
            this.Order = order;
            this.Slug = slug;
            this.UserLimit = userLimit;
            this.CreatorMetaData = creatorMetaData;
            this.Options = options;
            this.Variables = variables;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Ident = ident;
            this.VipStatus = vipStatus;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>6276316</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>test package 101</example>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /// <example>&lt;p&gt;this is just a test. only a test. nothing more.&lt;/p&gt;</example>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name = "image", EmitDefaultValue = false)]
        public string Image { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        /// <example>single</example>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public PackageCategory Category { get; set; }

        /// <summary>
        /// Gets or Sets BasePrice
        /// </summary>
        /// <example>5</example>
        [DataMember(Name = "base_price", EmitDefaultValue = false)]
        public float BasePrice { get; set; }

        /// <summary>
        /// Gets or Sets SalesTax
        /// </summary>
        /// <example>0</example>
        [DataMember(Name = "sales_tax", EmitDefaultValue = false)]
        public float SalesTax { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrice
        /// </summary>
        /// <example>5</example>
        [DataMember(Name = "total_price", EmitDefaultValue = false)]
        public float TotalPrice { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        /// <example>USD</example>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// If this package is part of a tiered category, this is the difference on upgrade pricing from the current active tier.
        /// </summary>
        /// <value>If this package is part of a tiered category, this is the difference on upgrade pricing from the current active tier.</value>
        [DataMember(Name = "prorate_price", EmitDefaultValue = false)]
        public float ProratePrice { get; set; }

        /// <summary>
        /// Gets or Sets Discount
        /// </summary>
        /// <example>0</example>
        [DataMember(Name = "discount", EmitDefaultValue = false)]
        public float Discount { get; set; }

        /// <summary>
        /// Gets or Sets DisableQuantity
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "disable_quantity", EmitDefaultValue = true)]
        public bool DisableQuantity { get; set; }

        /// <summary>
        /// Gets or Sets DisableGifting
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "disable_gifting", EmitDefaultValue = true)]
        public bool DisableGifting { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name = "expiration_date", EmitDefaultValue = false)]
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets Media
        /// </summary>
        [DataMember(Name = "media", EmitDefaultValue = false)]
        public List<PackageMedia> Media { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name = "slug", EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets UserLimit
        /// </summary>
        [DataMember(Name = "user_limit", EmitDefaultValue = false)]
        public int UserLimit { get; set; }

        /// <summary>
        /// Gets or Sets CreatorMetaData
        /// </summary>
        [DataMember(Name = "creator_meta_data", EmitDefaultValue = false)]
        public Object CreatorMetaData { get; set; }

        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [DataMember(Name = "options", EmitDefaultValue = false)]
        public List<string> Options { get; set; }

        /// <summary>
        /// Gets or Sets Variables
        /// </summary>
        [DataMember(Name = "variables", EmitDefaultValue = false)]
        public List<string> Variables { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /// <example>2024-05-21T18:09:17+00:00</example>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /// <example>2024-05-21T18:09:17+00:00</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// The package&#39;s string identifier.
        /// </summary>
        /// <value>The package&#39;s string identifier.</value>
        /// <example>pkg_3081120_7088903</example>
        [DataMember(Name = "ident", EmitDefaultValue = false)]
        public string Ident { get; set; }

        /// <summary>
        /// The package&#39;s VIP status. Only &#x60;null&#x60; has been observed so far, so the non-null type is unconfirmed.
        /// </summary>
        /// <value>The package&#39;s VIP status. Only &#x60;null&#x60; has been observed so far, so the non-null type is unconfirmed.</value>
        [DataMember(Name = "vip_status", EmitDefaultValue = false)]
        public string VipStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Package {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  BasePrice: ").Append(BasePrice).Append("\n");
            sb.Append("  SalesTax: ").Append(SalesTax).Append("\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ProratePrice: ").Append(ProratePrice).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("  DisableQuantity: ").Append(DisableQuantity).Append("\n");
            sb.Append("  DisableGifting: ").Append(DisableGifting).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  Media: ").Append(Media).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  UserLimit: ").Append(UserLimit).Append("\n");
            sb.Append("  CreatorMetaData: ").Append(CreatorMetaData).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Ident: ").Append(Ident).Append("\n");
            sb.Append("  VipStatus: ").Append(VipStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
