/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TebexHeadless.Client.OpenAPIDateConverter;

namespace TebexHeadless.Model
{
    /// <summary>
    /// TextboxData
    /// </summary>
    [DataContract(Name = "TextboxData")]
    public partial class TextboxData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextboxData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TextboxData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TextboxData" /> class.
        /// </summary>
        /// <param name="header">header (required).</param>
        /// <param name="text">HTML supported. (required).</param>
        public TextboxData(string header = default(string), string text = default(string))
        {
            // to ensure "header" is required (not null)
            if (header == null)
            {
                throw new ArgumentNullException("header is a required property for TextboxData and cannot be null");
            }
            this.Header = header;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for TextboxData and cannot be null");
            }
            this.Text = text;
        }

        /// <summary>
        /// Gets or Sets Header
        /// </summary>
        /// <example>Modules</example>
        [DataMember(Name = "header", IsRequired = true, EmitDefaultValue = true)]
        public string Header { get; set; }

        /// <summary>
        /// HTML supported.
        /// </summary>
        /// <value>HTML supported.</value>
        /// <example>You can configure the sidebar of your webstore by going to &lt;strong&gt;Webstore&lt;/strong&gt; &amp;gt; &lt;strong&gt;Design&lt;/strong&gt; &amp;gt; &lt;strong&gt;Modules&lt;/strong&gt;.</example>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextboxData {\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
