/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TebexHeadless.Model;
using TebexHeadless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TebexHeadless.Test.Model
{
    /// <summary>
    ///  Class for testing Basket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BasketTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Basket
        //private Basket instance;

        public BasketTests()
        {
            // TODO uncomment below to create an instance of Basket
            //instance = new Basket();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Basket
        /// </summary>
        [Fact]
        public void BasketInstanceTest()
        {
            // TODO uncomment below to test "IsType" Basket
            //Assert.IsType<Basket>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Ident'
        /// </summary>
        [Fact]
        public void IdentTest()
        {
            // TODO unit test for the property 'Ident'
        }

        /// <summary>
        /// Test the property 'Complete'
        /// </summary>
        [Fact]
        public void CompleteTest()
        {
            // TODO unit test for the property 'Complete'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Coupons'
        /// </summary>
        [Fact]
        public void CouponsTest()
        {
            // TODO unit test for the property 'Coupons'
        }

        /// <summary>
        /// Test the property 'Giftcards'
        /// </summary>
        [Fact]
        public void GiftcardsTest()
        {
            // TODO unit test for the property 'Giftcards'
        }

        /// <summary>
        /// Test the property 'CreatorCode'
        /// </summary>
        [Fact]
        public void CreatorCodeTest()
        {
            // TODO unit test for the property 'CreatorCode'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }

        /// <summary>
        /// Test the property 'CompleteUrl'
        /// </summary>
        [Fact]
        public void CompleteUrlTest()
        {
            // TODO unit test for the property 'CompleteUrl'
        }

        /// <summary>
        /// Test the property 'CompleteAutoRedirect'
        /// </summary>
        [Fact]
        public void CompleteAutoRedirectTest()
        {
            // TODO unit test for the property 'CompleteAutoRedirect'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }

        /// <summary>
        /// Test the property 'UsernameId'
        /// </summary>
        [Fact]
        public void UsernameIdTest()
        {
            // TODO unit test for the property 'UsernameId'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'SalesTax'
        /// </summary>
        [Fact]
        public void SalesTaxTest()
        {
            // TODO unit test for the property 'SalesTax'
        }

        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Fact]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Packages'
        /// </summary>
        [Fact]
        public void PackagesTest()
        {
            // TODO unit test for the property 'Packages'
        }

        /// <summary>
        /// Test the property 'Custom'
        /// </summary>
        [Fact]
        public void CustomTest()
        {
            // TODO unit test for the property 'Custom'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
    }
}
