/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TebexHeadless.Model;
using TebexHeadless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TebexHeadless.Test.Model
{
    /// <summary>
    ///  Class for testing CommunityGoalData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommunityGoalDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommunityGoalData
        //private CommunityGoalData instance;

        public CommunityGoalDataTests()
        {
            // TODO uncomment below to create an instance of CommunityGoalData
            //instance = new CommunityGoalData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommunityGoalData
        /// </summary>
        [Fact]
        public void CommunityGoalDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommunityGoalData
            //Assert.IsType<CommunityGoalData>(instance);
        }

        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }

        /// <summary>
        /// Test the property 'BarStyle'
        /// </summary>
        [Fact]
        public void BarStyleTest()
        {
            // TODO unit test for the property 'BarStyle'
        }

        /// <summary>
        /// Test the property 'BarAnimated'
        /// </summary>
        [Fact]
        public void BarAnimatedTest()
        {
            // TODO unit test for the property 'BarAnimated'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }

        /// <summary>
        /// Test the property 'TotalPayments'
        /// </summary>
        [Fact]
        public void TotalPaymentsTest()
        {
            // TODO unit test for the property 'TotalPayments'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'TimesAchieved'
        /// </summary>
        [Fact]
        public void TimesAchievedTest()
        {
            // TODO unit test for the property 'TimesAchieved'
        }
    }
}
