/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TebexHeadless.Model;
using TebexHeadless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TebexHeadless.Test.Model
{
    /// <summary>
    ///  Class for testing FeaturedPackageModule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeaturedPackageModuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeaturedPackageModule
        //private FeaturedPackageModule instance;

        public FeaturedPackageModuleTests()
        {
            // TODO uncomment below to create an instance of FeaturedPackageModule
            //instance = new FeaturedPackageModule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeaturedPackageModule
        /// </summary>
        [Fact]
        public void FeaturedPackageModuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeaturedPackageModule
            //Assert.IsType<FeaturedPackageModule>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
