/*
 * Tebex Headless API
 *
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TebexHeadless.Model;
using TebexHeadless.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TebexHeadless.Test.Model
{
    /// <summary>
    ///  Class for testing SinglePackageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SinglePackageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SinglePackageResponse
        //private SinglePackageResponse instance;

        public SinglePackageResponseTests()
        {
            // TODO uncomment below to create an instance of SinglePackageResponse
            //instance = new SinglePackageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SinglePackageResponse
        /// </summary>
        [Fact]
        public void SinglePackageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SinglePackageResponse
            //Assert.IsType<SinglePackageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
