# coding: utf-8

"""
    Tebex Headless API

    The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.

    The version of the OpenAPI document: 2.0.1
    Contact: tebex-integrations@overwolf.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from TebexHeadless.models.community_goal_data import CommunityGoalData

class TestCommunityGoalData(unittest.TestCase):
    """CommunityGoalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityGoalData:
        """Test CommunityGoalData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityGoalData`
        """
        model = CommunityGoalData()
        if include_optional:
            return CommunityGoalData(
                header = 'Community Goal',
                bar_style = 'normal',
                bar_animated = True,
                percentage = 100,
                total_payments = 1.337,
                target = 1.337,
                times_achieved = 56
            )
        else:
            return CommunityGoalData(
                header = 'Community Goal',
                bar_style = 'normal',
                bar_animated = True,
                percentage = 100,
        )
        """

    def testCommunityGoalData(self):
        """Test CommunityGoalData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
