# coding: utf-8

"""
    Tebex Headless API

    The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.

    The version of the OpenAPI document: 2.0.1
    Contact: tebex-integrations@overwolf.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from TebexHeadless.models.apply_gift_card200_response import ApplyGiftCard200Response

class TestApplyGiftCard200Response(unittest.TestCase):
    """ApplyGiftCard200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyGiftCard200Response:
        """Test ApplyGiftCard200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyGiftCard200Response`
        """
        model = ApplyGiftCard200Response()
        if include_optional:
            return ApplyGiftCard200Response(
                success = True,
                message = 'Gift card applied successfully'
            )
        else:
            return ApplyGiftCard200Response(
        )
        """

    def testApplyGiftCard200Response(self):
        """Test ApplyGiftCard200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
