/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RevenueShare } from '../models/RevenueShare';
import { HttpFile } from '../http/http';

/**
* A package within an existing basket.
*/
export class BasketPackage {
    /**
    * The quantity of `package` in this basket. This is not the total quantity of overall items in the basket.
    */
    'qty'?: number;
    /**
    * The type of payment, either `single` for one-time payments or `subscription`.
    */
    'type'?: BasketPackageTypeEnum;
    /**
    * An array of payment destination objects describing how the purchase should be split between multiple wallets. **Only available with pre-agreement from Tebex.**
    */
    'revenueShare'?: Array<RevenueShare>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BasketPackageTypeEnum",
            "format": ""
        },
        {
            "name": "revenueShare",
            "baseName": "revenue_share",
            "type": "Array<RevenueShare>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BasketPackage.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BasketPackageTypeEnum {
    Single = 'single',
    Subscription = 'subscription'
}

