/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateBasketRequest {
    /**
    * A URL the user can return to when checkout is completed.
    */
    'completeUrl'?: string;
    /**
    * A URL the user can return to when cancelling checkout.
    */
    'cancelUrl'?: string;
    /**
    * Custom data you wish to associate with the basket. This data will be included with webhook responses and GET requests associated with the Basket.
    */
    'custom'?: any;
    /**
    * True if the user should automatically be redirected to the relevant complete/cancel URL
    */
    'completeAutoRedirect'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completeUrl",
            "baseName": "complete_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "cancelUrl",
            "baseName": "cancel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "any",
            "format": ""
        },
        {
            "name": "completeAutoRedirect",
            "baseName": "complete_auto_redirect",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateBasketRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

