/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PackageCategory } from '../models/PackageCategory';
import { HttpFile } from '../http/http';

export class Package {
    'id'?: number;
    'name'?: string;
    'description'?: string;
    'image'?: string | null;
    'type'?: string;
    'category'?: PackageCategory;
    'basePrice'?: number;
    'salesTax'?: number;
    'totalPrice'?: number;
    'currency'?: string;
    /**
    * If this package is part of a tiered category, this is the difference on upgrade pricing from the current active tier.
    */
    'proratePrice'?: number | null;
    'discount'?: number;
    'disableQuantity'?: boolean;
    'disableGifting'?: boolean;
    'expirationDate'?: Date | null;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "PackageCategory",
            "format": ""
        },
        {
            "name": "basePrice",
            "baseName": "base_price",
            "type": "number",
            "format": "float"
        },
        {
            "name": "salesTax",
            "baseName": "sales_tax",
            "type": "number",
            "format": "float"
        },
        {
            "name": "totalPrice",
            "baseName": "total_price",
            "type": "number",
            "format": "float"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "proratePrice",
            "baseName": "prorate_price",
            "type": "number",
            "format": "float"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "number",
            "format": "float"
        },
        {
            "name": "disableQuantity",
            "baseName": "disable_quantity",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "disableGifting",
            "baseName": "disable_gifting",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Package.attributeTypeMap;
    }

    public constructor() {
    }
}

