/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Players model module.
 * @module TebexHeadless/model/Players
 * @version 2.0.1
 */
class Players {
    /**
     * Constructs a new <code>Players</code>.
     * @alias module:TebexHeadless/model/Players
     * @param online {Number} 
     * @param max {Number} 
     */
    constructor(online, max) { 
        
        Players.initialize(this, online, max);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, online, max) { 
        obj['online'] = online;
        obj['max'] = max;
    }

    /**
     * Constructs a <code>Players</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:TebexHeadless/model/Players} obj Optional instance to populate.
     * @return {module:TebexHeadless/model/Players} The populated <code>Players</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Players();

            if (data.hasOwnProperty('online')) {
                obj['online'] = ApiClient.convertToType(data['online'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Players</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Players</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Players.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

Players.RequiredProperties = ["online", "max"];

/**
 * @member {Number} online
 */
Players.prototype['online'] = undefined;

/**
 * @member {Number} max
 */
Players.prototype['max'] = undefined;






export default Players;

