/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModuleBase from './ModuleBase';
import RecentPaymentsData from './RecentPaymentsData';

/**
 * The RecentPaymentsModule model module.
 * @module TebexHeadless/model/RecentPaymentsModule
 * @version 2.0.1
 */
class RecentPaymentsModule {
    /**
     * Constructs a new <code>RecentPaymentsModule</code>.
     * @alias module:TebexHeadless/model/RecentPaymentsModule
     * @implements module:TebexHeadless/model/ModuleBase
     * @param id {Number} 
     * @param type {Object} 
     * @param startTime {Date} 
     * @param data {module:TebexHeadless/model/RecentPaymentsData} 
     */
    constructor(id, type, startTime, data) { 
        ModuleBase.initialize(this, id, type, startTime, data);
        RecentPaymentsModule.initialize(this, id, type, startTime, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, type, startTime, data) { 
        obj['id'] = id;
        obj['type'] = type;
        obj['start_time'] = startTime;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>RecentPaymentsModule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:TebexHeadless/model/RecentPaymentsModule} obj Optional instance to populate.
     * @return {module:TebexHeadless/model/RecentPaymentsModule} The populated <code>RecentPaymentsModule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecentPaymentsModule();
            ModuleBase.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Date');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = RecentPaymentsData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecentPaymentsModule</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecentPaymentsModule</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RecentPaymentsModule.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          RecentPaymentsData.validateJSON(data['data']);
        }

        return true;
    }


}

RecentPaymentsModule.RequiredProperties = ["id", "type", "start_time", "data"];

/**
 * @member {Number} id
 */
RecentPaymentsModule.prototype['id'] = undefined;

/**
 * @member {Object} type
 */
RecentPaymentsModule.prototype['type'] = undefined;

/**
 * @member {Date} start_time
 */
RecentPaymentsModule.prototype['start_time'] = undefined;

/**
 * Nullable; when null the module is ongoing.
 * @member {Date} end_time
 */
RecentPaymentsModule.prototype['end_time'] = undefined;

/**
 * @member {module:TebexHeadless/model/RecentPaymentsData} data
 */
RecentPaymentsModule.prototype['data'] = undefined;


// Implement ModuleBase interface:
/**
 * @member {Number} id
 */
ModuleBase.prototype['id'] = undefined;
/**
 * Discriminator for module kind.
 * @member {String} type
 */
ModuleBase.prototype['type'] = undefined;
/**
 * @member {Date} start_time
 */
ModuleBase.prototype['start_time'] = undefined;
/**
 * Nullable; when null the module is ongoing.
 * @member {Date} end_time
 */
ModuleBase.prototype['end_time'] = undefined;
/**
 * Type-specific payload.
 * @member {Object} data
 */
ModuleBase.prototype['data'] = undefined;




export default RecentPaymentsModule;

