/**
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TextboxData model module.
 * @module TebexHeadless/model/TextboxData
 * @version 2.0.1
 */
class TextboxData {
    /**
     * Constructs a new <code>TextboxData</code>.
     * @alias module:TebexHeadless/model/TextboxData
     * @param header {String} 
     * @param text {String} HTML supported.
     */
    constructor(header, text) { 
        
        TextboxData.initialize(this, header, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, header, text) { 
        obj['header'] = header;
        obj['text'] = text;
    }

    /**
     * Constructs a <code>TextboxData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:TebexHeadless/model/TextboxData} obj Optional instance to populate.
     * @return {module:TebexHeadless/model/TextboxData} The populated <code>TextboxData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextboxData();

            if (data.hasOwnProperty('header')) {
                obj['header'] = ApiClient.convertToType(data['header'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TextboxData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TextboxData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TextboxData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['header'] && !(typeof data['header'] === 'string' || data['header'] instanceof String)) {
            throw new Error("Expected the field `header` to be a primitive type in the JSON string but got " + data['header']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}

TextboxData.RequiredProperties = ["header", "text"];

/**
 * @member {String} header
 */
TextboxData.prototype['header'] = undefined;

/**
 * HTML supported.
 * @member {String} text
 */
TextboxData.prototype['text'] = undefined;






export default TextboxData;

