/*
Tebex Headless API

The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.

API version: 1.1.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexHeadless

import (
	"encoding/json"
)

// checks if the TierStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TierStatus{}

// TierStatus struct for TierStatus
type TierStatus struct {
	Id *float32 `json:"id,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewTierStatus instantiates a new TierStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTierStatus() *TierStatus {
	this := TierStatus{}
	return &this
}

// NewTierStatusWithDefaults instantiates a new TierStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTierStatusWithDefaults() *TierStatus {
	this := TierStatus{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TierStatus) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TierStatus) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TierStatus) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *TierStatus) SetId(v float32) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TierStatus) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TierStatus) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TierStatus) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TierStatus) SetDescription(v string) {
	o.Description = &v
}

func (o TierStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TierStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableTierStatus struct {
	value *TierStatus
	isSet bool
}

func (v NullableTierStatus) Get() *TierStatus {
	return v.value
}

func (v *NullableTierStatus) Set(val *TierStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTierStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTierStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTierStatus(val *TierStatus) *NullableTierStatus {
	return &NullableTierStatus{value: val, isSet: true}
}

func (v NullableTierStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTierStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


