/*
Tebex Headless API

The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.

API version: 2.0.1
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexHeadless

import (
	"encoding/json"
	"time"
)

// checks if the Package type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Package{}

// Package struct for Package
type Package struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Image *string `json:"image,omitempty"`
	Type *string `json:"type,omitempty"`
	Category *PackageCategory `json:"category,omitempty"`
	BasePrice *float32 `json:"base_price,omitempty"`
	SalesTax *float32 `json:"sales_tax,omitempty"`
	TotalPrice *float32 `json:"total_price,omitempty"`
	Currency *string `json:"currency,omitempty"`
	// If this package is part of a tiered category, this is the difference on upgrade pricing from the current active tier.
	ProratePrice *float32 `json:"prorate_price,omitempty"`
	Discount *float32 `json:"discount,omitempty"`
	DisableQuantity *bool `json:"disable_quantity,omitempty"`
	DisableGifting *bool `json:"disable_gifting,omitempty"`
	ExpirationDate *time.Time `json:"expiration_date,omitempty"`
	Media []PackageMedia `json:"media,omitempty"`
	Order *int32 `json:"order,omitempty"`
	Slug *string `json:"slug,omitempty"`
	UserLimit *int32 `json:"user_limit,omitempty"`
	CreatorMetaData map[string]interface{} `json:"creator_meta_data,omitempty"`
	Options []string `json:"options,omitempty"`
	Variables []string `json:"variables,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The package's string identifier.
	Ident *string `json:"ident,omitempty"`
	// The package's VIP status. Only `null` has been observed so far, so the non-null type is unconfirmed.
	VipStatus *string `json:"vip_status,omitempty"`
}

// NewPackage instantiates a new Package object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackage() *Package {
	this := Package{}
	return &this
}

// NewPackageWithDefaults instantiates a new Package object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageWithDefaults() *Package {
	this := Package{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Package) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Package) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Package) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Package) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Package) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Package) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Package) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Package) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Package) SetDescription(v string) {
	o.Description = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Package) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Package) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *Package) SetImage(v string) {
	o.Image = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Package) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Package) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Package) SetType(v string) {
	o.Type = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Package) GetCategory() PackageCategory {
	if o == nil || IsNil(o.Category) {
		var ret PackageCategory
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetCategoryOk() (*PackageCategory, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Package) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given PackageCategory and assigns it to the Category field.
func (o *Package) SetCategory(v PackageCategory) {
	o.Category = &v
}

// GetBasePrice returns the BasePrice field value if set, zero value otherwise.
func (o *Package) GetBasePrice() float32 {
	if o == nil || IsNil(o.BasePrice) {
		var ret float32
		return ret
	}
	return *o.BasePrice
}

// GetBasePriceOk returns a tuple with the BasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetBasePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.BasePrice) {
		return nil, false
	}
	return o.BasePrice, true
}

// HasBasePrice returns a boolean if a field has been set.
func (o *Package) HasBasePrice() bool {
	if o != nil && !IsNil(o.BasePrice) {
		return true
	}

	return false
}

// SetBasePrice gets a reference to the given float32 and assigns it to the BasePrice field.
func (o *Package) SetBasePrice(v float32) {
	o.BasePrice = &v
}

// GetSalesTax returns the SalesTax field value if set, zero value otherwise.
func (o *Package) GetSalesTax() float32 {
	if o == nil || IsNil(o.SalesTax) {
		var ret float32
		return ret
	}
	return *o.SalesTax
}

// GetSalesTaxOk returns a tuple with the SalesTax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetSalesTaxOk() (*float32, bool) {
	if o == nil || IsNil(o.SalesTax) {
		return nil, false
	}
	return o.SalesTax, true
}

// HasSalesTax returns a boolean if a field has been set.
func (o *Package) HasSalesTax() bool {
	if o != nil && !IsNil(o.SalesTax) {
		return true
	}

	return false
}

// SetSalesTax gets a reference to the given float32 and assigns it to the SalesTax field.
func (o *Package) SetSalesTax(v float32) {
	o.SalesTax = &v
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise.
func (o *Package) GetTotalPrice() float32 {
	if o == nil || IsNil(o.TotalPrice) {
		var ret float32
		return ret
	}
	return *o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetTotalPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalPrice) {
		return nil, false
	}
	return o.TotalPrice, true
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *Package) HasTotalPrice() bool {
	if o != nil && !IsNil(o.TotalPrice) {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given float32 and assigns it to the TotalPrice field.
func (o *Package) SetTotalPrice(v float32) {
	o.TotalPrice = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Package) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Package) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Package) SetCurrency(v string) {
	o.Currency = &v
}

// GetProratePrice returns the ProratePrice field value if set, zero value otherwise.
func (o *Package) GetProratePrice() float32 {
	if o == nil || IsNil(o.ProratePrice) {
		var ret float32
		return ret
	}
	return *o.ProratePrice
}

// GetProratePriceOk returns a tuple with the ProratePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetProratePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.ProratePrice) {
		return nil, false
	}
	return o.ProratePrice, true
}

// HasProratePrice returns a boolean if a field has been set.
func (o *Package) HasProratePrice() bool {
	if o != nil && !IsNil(o.ProratePrice) {
		return true
	}

	return false
}

// SetProratePrice gets a reference to the given float32 and assigns it to the ProratePrice field.
func (o *Package) SetProratePrice(v float32) {
	o.ProratePrice = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *Package) GetDiscount() float32 {
	if o == nil || IsNil(o.Discount) {
		var ret float32
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetDiscountOk() (*float32, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *Package) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given float32 and assigns it to the Discount field.
func (o *Package) SetDiscount(v float32) {
	o.Discount = &v
}

// GetDisableQuantity returns the DisableQuantity field value if set, zero value otherwise.
func (o *Package) GetDisableQuantity() bool {
	if o == nil || IsNil(o.DisableQuantity) {
		var ret bool
		return ret
	}
	return *o.DisableQuantity
}

// GetDisableQuantityOk returns a tuple with the DisableQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetDisableQuantityOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableQuantity) {
		return nil, false
	}
	return o.DisableQuantity, true
}

// HasDisableQuantity returns a boolean if a field has been set.
func (o *Package) HasDisableQuantity() bool {
	if o != nil && !IsNil(o.DisableQuantity) {
		return true
	}

	return false
}

// SetDisableQuantity gets a reference to the given bool and assigns it to the DisableQuantity field.
func (o *Package) SetDisableQuantity(v bool) {
	o.DisableQuantity = &v
}

// GetDisableGifting returns the DisableGifting field value if set, zero value otherwise.
func (o *Package) GetDisableGifting() bool {
	if o == nil || IsNil(o.DisableGifting) {
		var ret bool
		return ret
	}
	return *o.DisableGifting
}

// GetDisableGiftingOk returns a tuple with the DisableGifting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetDisableGiftingOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableGifting) {
		return nil, false
	}
	return o.DisableGifting, true
}

// HasDisableGifting returns a boolean if a field has been set.
func (o *Package) HasDisableGifting() bool {
	if o != nil && !IsNil(o.DisableGifting) {
		return true
	}

	return false
}

// SetDisableGifting gets a reference to the given bool and assigns it to the DisableGifting field.
func (o *Package) SetDisableGifting(v bool) {
	o.DisableGifting = &v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *Package) GetExpirationDate() time.Time {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetExpirationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *Package) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given time.Time and assigns it to the ExpirationDate field.
func (o *Package) SetExpirationDate(v time.Time) {
	o.ExpirationDate = &v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *Package) GetMedia() []PackageMedia {
	if o == nil || IsNil(o.Media) {
		var ret []PackageMedia
		return ret
	}
	return o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetMediaOk() ([]PackageMedia, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *Package) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given []PackageMedia and assigns it to the Media field.
func (o *Package) SetMedia(v []PackageMedia) {
	o.Media = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Package) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Package) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *Package) SetOrder(v int32) {
	o.Order = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *Package) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *Package) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *Package) SetSlug(v string) {
	o.Slug = &v
}

// GetUserLimit returns the UserLimit field value if set, zero value otherwise.
func (o *Package) GetUserLimit() int32 {
	if o == nil || IsNil(o.UserLimit) {
		var ret int32
		return ret
	}
	return *o.UserLimit
}

// GetUserLimitOk returns a tuple with the UserLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetUserLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.UserLimit) {
		return nil, false
	}
	return o.UserLimit, true
}

// HasUserLimit returns a boolean if a field has been set.
func (o *Package) HasUserLimit() bool {
	if o != nil && !IsNil(o.UserLimit) {
		return true
	}

	return false
}

// SetUserLimit gets a reference to the given int32 and assigns it to the UserLimit field.
func (o *Package) SetUserLimit(v int32) {
	o.UserLimit = &v
}

// GetCreatorMetaData returns the CreatorMetaData field value if set, zero value otherwise.
func (o *Package) GetCreatorMetaData() map[string]interface{} {
	if o == nil || IsNil(o.CreatorMetaData) {
		var ret map[string]interface{}
		return ret
	}
	return o.CreatorMetaData
}

// GetCreatorMetaDataOk returns a tuple with the CreatorMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetCreatorMetaDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CreatorMetaData) {
		return map[string]interface{}{}, false
	}
	return o.CreatorMetaData, true
}

// HasCreatorMetaData returns a boolean if a field has been set.
func (o *Package) HasCreatorMetaData() bool {
	if o != nil && !IsNil(o.CreatorMetaData) {
		return true
	}

	return false
}

// SetCreatorMetaData gets a reference to the given map[string]interface{} and assigns it to the CreatorMetaData field.
func (o *Package) SetCreatorMetaData(v map[string]interface{}) {
	o.CreatorMetaData = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *Package) GetOptions() []string {
	if o == nil || IsNil(o.Options) {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *Package) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *Package) SetOptions(v []string) {
	o.Options = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *Package) GetVariables() []string {
	if o == nil || IsNil(o.Variables) {
		var ret []string
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetVariablesOk() ([]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *Package) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given []string and assigns it to the Variables field.
func (o *Package) SetVariables(v []string) {
	o.Variables = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Package) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Package) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Package) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Package) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Package) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Package) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetIdent returns the Ident field value if set, zero value otherwise.
func (o *Package) GetIdent() string {
	if o == nil || IsNil(o.Ident) {
		var ret string
		return ret
	}
	return *o.Ident
}

// GetIdentOk returns a tuple with the Ident field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetIdentOk() (*string, bool) {
	if o == nil || IsNil(o.Ident) {
		return nil, false
	}
	return o.Ident, true
}

// HasIdent returns a boolean if a field has been set.
func (o *Package) HasIdent() bool {
	if o != nil && !IsNil(o.Ident) {
		return true
	}

	return false
}

// SetIdent gets a reference to the given string and assigns it to the Ident field.
func (o *Package) SetIdent(v string) {
	o.Ident = &v
}

// GetVipStatus returns the VipStatus field value if set, zero value otherwise.
func (o *Package) GetVipStatus() string {
	if o == nil || IsNil(o.VipStatus) {
		var ret string
		return ret
	}
	return *o.VipStatus
}

// GetVipStatusOk returns a tuple with the VipStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetVipStatusOk() (*string, bool) {
	if o == nil || IsNil(o.VipStatus) {
		return nil, false
	}
	return o.VipStatus, true
}

// HasVipStatus returns a boolean if a field has been set.
func (o *Package) HasVipStatus() bool {
	if o != nil && !IsNil(o.VipStatus) {
		return true
	}

	return false
}

// SetVipStatus gets a reference to the given string and assigns it to the VipStatus field.
func (o *Package) SetVipStatus(v string) {
	o.VipStatus = &v
}

func (o Package) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Package) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.BasePrice) {
		toSerialize["base_price"] = o.BasePrice
	}
	if !IsNil(o.SalesTax) {
		toSerialize["sales_tax"] = o.SalesTax
	}
	if !IsNil(o.TotalPrice) {
		toSerialize["total_price"] = o.TotalPrice
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.ProratePrice) {
		toSerialize["prorate_price"] = o.ProratePrice
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.DisableQuantity) {
		toSerialize["disable_quantity"] = o.DisableQuantity
	}
	if !IsNil(o.DisableGifting) {
		toSerialize["disable_gifting"] = o.DisableGifting
	}
	if !IsNil(o.ExpirationDate) {
		toSerialize["expiration_date"] = o.ExpirationDate
	}
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.UserLimit) {
		toSerialize["user_limit"] = o.UserLimit
	}
	if !IsNil(o.CreatorMetaData) {
		toSerialize["creator_meta_data"] = o.CreatorMetaData
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Ident) {
		toSerialize["ident"] = o.Ident
	}
	if !IsNil(o.VipStatus) {
		toSerialize["vip_status"] = o.VipStatus
	}
	return toSerialize, nil
}

type NullablePackage struct {
	value *Package
	isSet bool
}

func (v NullablePackage) Get() *Package {
	return v.value
}

func (v *NullablePackage) Set(val *Package) {
	v.value = val
	v.isSet = true
}

func (v NullablePackage) IsSet() bool {
	return v.isSet
}

func (v *NullablePackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackage(val *Package) *NullablePackage {
	return &NullablePackage{value: val, isSet: true}
}

func (v NullablePackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


