/*
Tebex Headless API

The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexHeadless

import (
	"encoding/json"
)

// checks if the UpdateTierRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTierRequest{}

// UpdateTierRequest struct for UpdateTierRequest
type UpdateTierRequest struct {
	PackageId *string `json:"package_id,omitempty"`
}

// NewUpdateTierRequest instantiates a new UpdateTierRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTierRequest() *UpdateTierRequest {
	this := UpdateTierRequest{}
	return &this
}

// NewUpdateTierRequestWithDefaults instantiates a new UpdateTierRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTierRequestWithDefaults() *UpdateTierRequest {
	this := UpdateTierRequest{}
	return &this
}

// GetPackageId returns the PackageId field value if set, zero value otherwise.
func (o *UpdateTierRequest) GetPackageId() string {
	if o == nil || IsNil(o.PackageId) {
		var ret string
		return ret
	}
	return *o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTierRequest) GetPackageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PackageId) {
		return nil, false
	}
	return o.PackageId, true
}

// HasPackageId returns a boolean if a field has been set.
func (o *UpdateTierRequest) HasPackageId() bool {
	if o != nil && !IsNil(o.PackageId) {
		return true
	}

	return false
}

// SetPackageId gets a reference to the given string and assigns it to the PackageId field.
func (o *UpdateTierRequest) SetPackageId(v string) {
	o.PackageId = &v
}

func (o UpdateTierRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTierRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PackageId) {
		toSerialize["package_id"] = o.PackageId
	}
	return toSerialize, nil
}

type NullableUpdateTierRequest struct {
	value *UpdateTierRequest
	isSet bool
}

func (v NullableUpdateTierRequest) Get() *UpdateTierRequest {
	return v.value
}

func (v *NullableUpdateTierRequest) Set(val *UpdateTierRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTierRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTierRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTierRequest(val *UpdateTierRequest) *NullableUpdateTierRequest {
	return &NullableUpdateTierRequest{value: val, isSet: true}
}

func (v NullableUpdateTierRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTierRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


