/*
Tebex Headless API

The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexHeadless

import (
	"encoding/json"
)

// checks if the CMSPagesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CMSPagesResponse{}

// CMSPagesResponse struct for CMSPagesResponse
type CMSPagesResponse struct {
	Data []CMSPage `json:"data,omitempty"`
}

// NewCMSPagesResponse instantiates a new CMSPagesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCMSPagesResponse() *CMSPagesResponse {
	this := CMSPagesResponse{}
	return &this
}

// NewCMSPagesResponseWithDefaults instantiates a new CMSPagesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCMSPagesResponseWithDefaults() *CMSPagesResponse {
	this := CMSPagesResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CMSPagesResponse) GetData() []CMSPage {
	if o == nil || IsNil(o.Data) {
		var ret []CMSPage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CMSPagesResponse) GetDataOk() ([]CMSPage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CMSPagesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CMSPage and assigns it to the Data field.
func (o *CMSPagesResponse) SetData(v []CMSPage) {
	o.Data = v
}

func (o CMSPagesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CMSPagesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCMSPagesResponse struct {
	value *CMSPagesResponse
	isSet bool
}

func (v NullableCMSPagesResponse) Get() *CMSPagesResponse {
	return v.value
}

func (v *NullableCMSPagesResponse) Set(val *CMSPagesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCMSPagesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCMSPagesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCMSPagesResponse(val *CMSPagesResponse) *NullableCMSPagesResponse {
	return &NullableCMSPagesResponse{value: val, isSet: true}
}

func (v NullableCMSPagesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCMSPagesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


