/*
Tebex Headless API

The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), or from a backend server, such as for in-game GUIs.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexHeadless

import (
	"encoding/json"
)

// checks if the UpdateTierResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTierResponse{}

// UpdateTierResponse struct for UpdateTierResponse
type UpdateTierResponse struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUpdateTierResponse instantiates a new UpdateTierResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTierResponse() *UpdateTierResponse {
	this := UpdateTierResponse{}
	return &this
}

// NewUpdateTierResponseWithDefaults instantiates a new UpdateTierResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTierResponseWithDefaults() *UpdateTierResponse {
	this := UpdateTierResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateTierResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTierResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateTierResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateTierResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateTierResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTierResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateTierResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateTierResponse) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateTierResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTierResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpdateTierResponse struct {
	value *UpdateTierResponse
	isSet bool
}

func (v NullableUpdateTierResponse) Get() *UpdateTierResponse {
	return v.value
}

func (v *NullableUpdateTierResponse) Set(val *UpdateTierResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTierResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTierResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTierResponse(val *UpdateTierResponse) *NullableUpdateTierResponse {
	return &NullableUpdateTierResponse{value: val, isSet: true}
}

func (v NullableUpdateTierResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTierResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


